### PR TITLE
pinar lab member profile

### PR DESCRIPTION
**Pull request by poe4**

### CODE REVIEW

**Comment by manzt** [comment]
Hey @poe4! I'm updating some information on the lab website and noticed that you this still hasn't been merged.

I see that the last commit includes `firstname-lastname.md`, which seems to be a template file that was committed by accident. Are you able to delete this file and push the latest changes? That way we won't have a "First Last" Student listed in the group members:

image


Otherwise the PR looks great! Preview:

image


Let me know if there is anything I can do to help!

**Comment by ngehlenborg** [comment]
The `firstname-lastname.md` should not be included. @poe4: can you remove that from the PR and resubmit?

**Comment by poe4** [comment]
Hi @manzt, @ngehlenborg! I am so sorry for the error, and subsequent delay in resolving it. I just got home from traveling for a family emergency, and unfortunately did not have the machine with the erroneous file with me on the trip. I just deleted the file and pushed the updates--@manzt, could you please let me know if it didn't work? Thank you so much, and my apologies again for the holdup.

**Comment by manzt** [comment]
No problem at all! Just noticed it hadn't been merged – didn't mean to add additional stress to this challenging time. 

The changes are appropriate, but the latest commit added another image file. There is now both:

- [assets/img/members/fullsize/pinar-eser-aspectratio.png](https://github.com/hms-dbmi/gehlenborglab-website/pull/312/files#diff-4a65ef3cef1dd5e013d6fee586e854991feb6d023226f0d0cb4849d179323327)
- [assets/img/members/fullsize/pinar-eser.png](https://github.com/hms-dbmi/gehlenborglab-website/pull/312/files#diff-10a919186e589ac541b06fb435cfa4bcf137ae42219b11d2b7217fb5cd18f73f)

The latter is the only one which ends up getting used in the site:

https://github.com/poe4/gehlenborglab-website/blob/adfa9420f120812a57f0c29597897496753edef9/_members/pinar-eser.md?plain=1#L5

We only need one file for the site. I'm guessing that you'd like to keep the `aspectratio` version? In that case, you can just delete the preview file and rename `pinar-eser-aspectratio.png` -> `pinar-eser.png`. Once you've made that change, please commit and push the latest, then we can merge.

**Comment by poe4** [comment]
Thanks for catching this, Trevor! Better now?

**Comment by manzt** [comment]
Yup, looks good to me! @ngehlenborg

**Comment by poe4** [comment]
Thanks so much!

**Comment by ngehlenborg** [comment]
Looking good!

**Pull request merged**
