### PR TITLE
Ilan profile caption update with image

### PR DESCRIPTION
**Pull request by ilan-gold**

### CODE REVIEW

**Comment by ilan-gold** [comment]
I updated the file to jpg.  I will also set up a dev environment if this doesn't work so you don't have to keep testing this for me.

**Comment by ngehlenborg** [comment]
The tests are still failing. @ilan-gold can you look into that?

**Comment by ilan-gold** [comment]
Updated - the tests should pass but I don't know if the photo is good (@mccalluc said before it wasn't working).  I'll set up a dev environment to make sure it works.

**Comment by ilan-gold** [comment]
@ngehlenborg @mccalluc  updated the photo - should be good now.

**Pull request merged**
