### PR TITLE
Replace Max with PJ as curriculum fellow

### PR DESCRIPTION
**Pull request by pieterjanvc**

### CODE REVIEW

**Review by manzt — APPROVED** [review]
Looks good to me (I'm not able to merge).

**Comment by john-conroy** [comment]
@pieterjanvc Do you want to add a blurb for your 'Biography' section?

**Comment by pieterjanvc** [comment]
Hi,

Made the updates to my bio and set Max's end-date

**Comment by pieterjanvc** [comment]
Thanks,

Upon review, I can see that my profile is shown now, but the Markdown links do not seem to render (only plain text). Also Max Wolf's profile is still on there. He should be in the alumni section but I thought this would happen automatically when I set an end date.

Would you like me to start a new Pull request for this?

**Comment by john-conroy** [comment]
Which links are you referring to? Feel free to make a PR. I'll probably do some broader scale clean-up after talking to Nils.

**Pull request merged**
