### PR TITLE
Add Cev paper

### PR DESCRIPTION
**Pull request by manzt**

### CODE REVIEW

**Comment by sehilyi** [comment]
(interesting error...)

**Comment by manzt** [comment]
Yes... I think this has to do with the compression for the jpg.

**Comment by manzt** [comment]
It built without the image

**Comment by manzt** [comment]
@sehilyi .... I just recompressed the image and it seems to be working

**Review by sehilyi — APPROVED** [review]
Interesting.. But good to know the source of the issue

**Pull request merged**
